[package]
name = "mcpacker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.4", features = ["derive", "string"] }
glob = "0.3.1"
notify = "6.1.1"
rayon = "1.10.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
shellexpand = { version = "3.1.0", features = ["path"] }
symlink = "0.1.0"
toml = "0.8.12"
zip = "2.1.1"
